//SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

/// @title Wefa Project interface.
/// @dev Interface of a Wefa Project  contract.
interface IProject {
  enum Goal {
    RESTORATION,
    CONSERVATION,
    PRESERVATION,
    CULTIVATION,
    ENERGY_REDUCTION,
    RECYCLING
  }

  enum Category {
    GROUND_BIOMASS_CARBON_SEQUESTRATION,
    EXTENDED_GROWING_SEASON,
    ANIMAL_BIODIVERSITY,
    ANIMAL_WELFARE,
    DROUGHT_RESILIENCE,
    ECOSYSTEM_HEALTH,
    FIRE_RESILIENCE,
    GROUND_COVER,
    PEST_RESILIENCE,
    PLANT_BIODIVERSITY,
    VEGETATION_TRANSITION,
    SOIL_HEALTH,
    WATER_FILTRATION,
    INDIGENOUS_RIGHTS,
    REDUCED_CHEMICAL_RUNOFF,
    REDUCED_FLOODING,
    REDUCED_SOIL_EROSION,
    SOCIAL_COBENEFITS,
    SOIL_ORRGANIC_CARBON_SEQUESTRATION
  }
}
